import { CameraFeed, Incident } from "./types";

export const MOCK_CAMERAS: CameraFeed[] = [
  {
    id: "cam-01",
    name: "CAM 01",
    location: "Highway 101 — Northbound",
    videoSrc: "/videos/feed1.mp4",
    status: "clear",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "cam-02",
    name: "CAM 02",
    location: "Interstate 280 — Exit 12",
    videoSrc: "/videos/feed2.mp4",
    status: "alert",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "cam-03",
    name: "CAM 03",
    location: "Downtown Junction — 5th & Main",
    videoSrc: "/videos/feed3.mp4",
    status: "clear",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "cam-04",
    name: "CAM 04",
    location: "Industrial Blvd — Sector 7",
    videoSrc: "/videos/feed4.mp4",
    status: "offline",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "cam-05",
    name: "CAM 05",
    location: "River Bridge — Westbound",
    videoSrc: "/videos/feed5.mp4",
    status: "clear",
    lastChecked: new Date().toISOString(),
  },
  {
    id: "cam-06",
    name: "CAM 06",
    location: "School Zone — Elm Street",
    videoSrc: "/videos/feed6.mp4",
    status: "alert",
    lastChecked: new Date().toISOString(),
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    cameraId: "cam-02",
    cameraName: "CAM 02",
    timestamp: new Date(Date.now() - 120000).toISOString(),
    severity: "Critical",
    type: "Multi-vehicle",
    description: "Three-vehicle pile-up detected on interstate exit ramp. Emergency services recommended immediately.",
    emergencyPriority: 9,
    acknowledged: false,
  },
  {
    id: "inc-002",
    cameraId: "cam-06",
    cameraName: "CAM 06",
    timestamp: new Date(Date.now() - 300000).toISOString(),
    severity: "High",
    type: "Pedestrian",
    description: "Pedestrian struck at crosswalk near school zone. Vehicle stopped at scene.",
    emergencyPriority: 8,
    acknowledged: false,
  },
  {
    id: "inc-003",
    cameraId: "cam-01",
    cameraName: "CAM 01",
    timestamp: new Date(Date.now() - 900000).toISOString(),
    severity: "Medium",
    type: "Hazard",
    description: "Debris on highway — large tire fragment obstructing right lane.",
    emergencyPriority: 5,
    acknowledged: true,
  },
  {
    id: "inc-004",
    cameraId: "cam-03",
    cameraName: "CAM 03",
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    severity: "Low",
    type: "Single-vehicle",
    description: "Minor fender-bender, vehicle pulled to shoulder. No injuries apparent.",
    emergencyPriority: 2,
    acknowledged: true,
  },
];
